version: '3.3'

services:
   database:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
       - "3309:3306"
   wordpress:
     depends_on:
       - database
     build:
       context: .
       dockerfile: bin/docker/images/woocommerce/Dockerfile
     volumes:
       - ./wordpress/core:/var/www/html
       - ./src:/var/www/html/wp-content/plugins/woocommerce_hipayenterprise
     ports:
       - "8000:80"
     restart: always
     env_file:
      - bin/docker/conf/development/hipay.env
      - bin/docker/conf/development/wordpress.env.sample
volumes:
    db_data: