image: hipay/gitlab-ci-base:jessie

stages:
#- package
- build
- deploy

build:
  stage: build
  before_script:
  - /tools/docker-rmi.sh ${REGISTRY_URL}/${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
  script:
  - docker-compose -f docker-compose.acceptance.yml build
  - docker-compose -f docker-compose.acceptance.yml push
  after_script:
  - docker rmi ${REGISTRY_URL}/${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
  tags:
  - pi-commerce-no-overlay

deploy2recette:
  stage: deploy
  before_script:
  - sed -i -e "s/{HIPAY_API_USER_RECETTE\}/$HIPAY_API_USER_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
  - sed -i -e "s/{HIPAY_API_PASSWORD_RECETTE\}/$HIPAY_API_PASSWORD_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
  - sed -i -e "s/{HIPAY_TOKENJS_PUBLICKEY_RECETTE\}/$HIPAY_TOKENJS_PUBLICKEY_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
  - sed -i -e "s/{HIPAY_TOKENJS_USERNAME_RECETTE\}/$HIPAY_TOKENJS_USERNAME_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
  - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_RECETTE\}/$HIPAY_SECRET_PASSPHRASE_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
  - sed -i -e "s/{DB_HOST\}/${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}_database/" ./docker-compose.acceptance.yml
  - sed -i "s/$(echo {HIPAY_SECRET_PASSPHRASE_RECETTE} | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo '$HIPAY_SECRET_PASSPHRASE_RE7' | sed -e 's/[\/&]/\\&/g')/g" ./bin/docker/conf/acceptance/hipay.env.sample
  # Substitute env variables which doesn't exists on the distant machine
  - /tools/substitute-env-var.sh docker-compose.acceptance.yml
  # Change path for relative path to environment files
  - sed -i -e "s|bin/docker/conf/acceptance/hipay.env.sample|hipay.env.sample|g" docker-compose.acceptance.yml
  script:
  - bash /tools/deployToDockerMachine.sh -e ./bin/docker/conf/acceptance/hipay.env.sample -s docker-compose.acceptance.yml -n $DOCKER_STACK-$DOCKER_SERVICE-$CI_COMMIT_REF_SLUG
  allow_failure: true
  tags:
  - pi-commerce-no-overlay
